### PR TITLE
feat: insert interested data to database

### LINKED ISSUE #36: Feat: Add interested button components on cards on explore page
### Description

Add interested button components on cards on explore page

### LINKED ISSUE #37: Feat: Already interested products should have a different button
### Description

disable the interested button if product alrady interested

### Screenshots

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by sboy99**
closes #36 
closes #37

### CODE REVIEW

**Comment by sboy99** [comment]
should be merged after merging #5

**Review by Aadarsh805 — APPROVED** [review]
looks good

**Comment by Aadarsh805** [comment]
btw there will be another product card for userprofile page and same card will be on account page but without button

**Comment by Aadarsh805** [comment]
what else remains on this pr @sboy99

**Comment by Aadarsh805** [comment]
tell me when ready for merge

**Pull request merged**
