### PR TITLE
Footer

### LINKED ISSUE #2: Feat: Create landing page
### Description

code landing page design according to the Figma design

### Screenshots

Desktop - 1(5)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Somidh**
## Fixes Issue

Closes #2 

## Changes proposed

- Added footer section

### CODE REVIEW

**Comment by Aadarsh805** [comment]
add ui credits in middle
ui credits: <browncolor href='dribble link'>dribble account user</>
image

**Comment by Aadarsh805** [comment]
increase icon size so that padding is less 
image

**Comment by Aadarsh805** [comment]
can we remove scrollbar ?
should we i mean

**Comment by Aadarsh805** [comment]
> can we remove scrollbar ? should we i mean

do it

**Comment by Somidh** [comment]
> > can we remove scrollbar ? should we i mean
> 
> do it

okay

**Pull request merged**
